### ISSUE TITLE
How to run these in Kodelife

### ISSUE THREAD

**Issue by heaversm** [keijiro/ShaderSketches#2]
Hi - these are great, but I was confused on how to open these in Kodelife. I couldn't find any of the examples that would actually run without Kodelife throwing errors.

**Comment by keijiro** [comment]
- Choose one of the fragment shaders from the `Fragment` directory.
- Copy the source code.
- Open "Fragment" pane in Kodelife.
- Select all and paste the code.

**Comment by geslotencirkel** [comment]
Maybe changed since 2018 so here is how I got it to work in KodeLife (0.9.1.132)

- Open KodeLife and select New from File menu option
- Leave Vertex tab alone and go to Fragment tab and copy paste a shader from this repo - in my example the boxes.glsl
- Define resolution and time above the code you paste - 

```
uniform float time;
uniform vec2 resolution;
```

- in Boxes.glsl they are called iResolution and iGlobalTime, so change these to "resolution" and "time" . If you leave them as is, it doesn't work, even if you define them above the code and in Vertex tab - don't know whats the reason but i am also not a golfer.
